### ISSUE TITLE
Can't add event bus listeners via method references

### ISSUE THREAD

**Issue by TheLimePixel** [autaut03/kottle#12] opened 2019-10-02 23:33 UTC
So, I've noticed that
```kotlin
FMLKotlinModLoadingContext.get().modEventBus.addListener<InterModProcessEvent> { processIMC(it) }
```
works as you'd expect it to, but
```kotlin
FMLKotlinModLoadingContext.get().modEventBus.addListene(this::processIMC)
```
causes a crash.

I was wondering if this is a bug or just a limitation.

**Comment by autaut03** [comment] 2019-10-03 11:31
Hey, thanks for reporting. Yes, this is a bug indeed and I'm aware of it, but I haven't had much time to look into it.

Closing this as a duplicate of https://github.com/autaut03/kottle/issues/8.

**Closed as completed by autaut03** 2019-10-03 11:31 UTC
